### ISSUE TITLE
Les graphiques en page d'accueil ne s'affichent pas

### ISSUE THREAD

**Issue by Lertsenem** [mellecrepe/banquelette#4]
J'ai créé un conteneur Docker avec la dernière version (sqlite) de Banquelette,
ajouté quelques données (ING-Direct). Les données sont correctement validées,
je peux les voir en sélectionnant 2015 > Octobre, mais elles n'apparaissent pas
sur les graphes en page d'accueil.

Peut-être lié au changement d'année ?

**Comment by mellecrepe** [comment]
La page d'accueil est prévu pour afficher que les stats de l'année en cours.
Il y avait une erreur d'affichage dans le titre, j'ai fait un correctif.

A terme je modifierai la page pour avoir plusieurs années
